const ITEMS = [
    {
        id: 1,
        nombre: 'Zapatillas',
        precio: 70.000,
        descripcion: 'A piece of bread',
        imagen: '../../assets/images/item-1.jpg',
        categoria: 'Ropa',
        oferta: 0,
        vendedor: 'Juan',
    },
    {
        id: 2,
        nombre: 'Camisa',
        precio: 40.000,
        descripcion: 'A piece of bread',
        imagen: '../../assets/images/item-1.jpg',
        categoria: 'Ropa',
        oferta: 0,
        vendedor: 'Pedro',
    },{
        id: 3,
        nombre: 'iPhone',
        precio: 900.000,
        descripcion: 'A piece of bread',
        imagen: '../../assets/images/item-1.jpg',
        categoria: 'Tecnologia',
        oferta: 0,
        vendedor: 'Catalina',
    },{
        id: 4,
        nombre: 'Anillo',
        precio: 600.000,
        descripcion: 'A piece of bread',
        imagen: '../../assets/images/item-1.jpg',
        categoria: 'Joyeria',
        oferta: 0,
        vendedor: 'Jesus',
    },
    {
        id: 5,
        nombre: 'Anillo',
        precio: 600.000,
        descripcion: 'A piece of bread',
        imagen: '../../assets/images/item-1.jpg',
        categoria: 'Joyeria',
        oferta: 0,
        vendedor: 'Jesus',
    },
]

export default ITEMS;